GET http://localhost:3000/coffees?limit=10&offset=0
###
GET http://localhost:3000/coffees/2
###
POST http://localhost:3000/coffees
Content-Type: application/json

{
    "name": "Cappuccino",
    "brand": "Starbucks",
    "flavors": [
        "Caramel",
        "Vanilla"
    ]
}

###
DELETE http://localhost:3000/coffees/2

###
PATCH http://localhost:3000/coffees/1
Content-Type: application/json

{
    "name": "Coffee#1"
}
