GET http://localhost:3000/coffees?limit=2&offset=2
###
GET http://localhost:3000/coffees/1a3
###
POST http://localhost:3000/coffees
Content-Type: application/json

{
  "name": "Coffee#6",
  "brand": "Starbucks",
  "flavors": [
    "Caramel",
    "Vanilla"
  ]
}

###
DELETE http://localhost:3000/coffees/2

###
PATCH http://localhost:3000/coffees/133
Content-Type: application/json
x-api-key: e2e4b8c0-0b8a-4b8c-8e2e-4b8c0b8c8e2e

{
  "flavors": [
    "Caramel",
    "Cardamom"
    ]
}
